name: DayCounter
version: '${version}'
main: de.greenman999.daycounter.DayCounter
description: A customisable DayCounter only counting days, when a player is online.
api-version: '1.20'
author: Greenman999
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true